import os
import json
import csv

def _get_text_from_autogen_subs(subtitle_file:str) -> str:
    """
    Get the full video captions as continuous text
    from the autogenerated youtube subtitles
    """
    pass

def _get_text_from_manual_subs(subtitle_file:str) -> str:
    """
    Get the full video captions as continuous text
    from manual youtube subtitles
    """
    pass

def _get_text_from_selfgen_subs(subtitle_file:str) -> str:
    """
    Get the full video captions as continuous text
    from self-generated subtitles
    """
    pass


def save_to_database(
        info_json,
        video_file,
        subtitle_files) -> None:
    """
    Save data to CSV file
    """
    ### Get subtitle text
    pass